### ISSUE TITLE
Getting Reports from Headless Tekla 

### ISSUE THREAD

**Issue by aditya84u** [TrimbleSolutionsCorporation/HeadlessTeklaStructuresExample#2]
Hi,
Just got started with the headless, We are able to connect to model query the project properties, write a report of the project properties. But when it comes to publishing reports out of model objects we get a blank file instead. So can you help us in this regard

**Comment by CarlosHerrero** [comment]
Hello,

Can you confirm that the method you are trying to use and it does not work is myPart.GetReportProperty() or Operation.CreateReportFromSelected() ?

**Comment by aditya84u** [comment]
Yes **Operation.** it is.

**Comment by CarlosHerrero** [comment]
Hello,

Could you share the code you used when calling that method?
Dev team informed that it should work.

**Comment by aditya84u** [comment]
Line of Code used 
bool test = Tekla.Structures.Model.Operations.Operation.CreateReportFromAll(@"path\350   Advanced Bill.rpt", @"C:\TeklaStructuresModels\MetricModel1\Reports\Test1", "", "", "");
But blank report obtained.



![TeklaHeadless](https://user-images.githubusercontent.com/25252294/57226329-72209a80-6fd4-11e9-84a3-cdd4b07315ea.jpg)

**Comment by CarlosHerrero** [comment]
Discussion continued in forum.tekla.com
